spring.application.name=SecureEms_backend
server.address=10.168.200.30
# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/secureems?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=pinky.learns@gmail.com
spring.mail.password=bpsp ugrt ipdb plpq

hr.email=harikanuganti9@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=mysecuresecretkeymysecuresecretkey123456789abcdef
jwt.expiration=86400000